# Generated by Django 4.2.7 on 2026-01-06 21:58

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_lote', models.CharField(help_text='Código único de identificación del lote', max_length=50, unique=True, verbose_name='Código del Lote')),
                ('ubicacion_cultivo', models.CharField(help_text='Dirección o coordenadas del cultivo', max_length=200, verbose_name='Ubicación del Cultivo')),
                ('fecha_cosecha', models.DateField(help_text='Fecha en que se cosechó el lote', verbose_name='Fecha de Cosecha')),
                ('observaciones', models.TextField(blank=True, help_text='Información adicional sobre el lote', null=True, verbose_name='Observaciones')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Registro')),
            ],
            options={
                'verbose_name': 'Lote',
                'verbose_name_plural': 'Lotes',
                'db_table': 'lotes',
                'ordering': ['-fecha_cosecha'],
            },
        ),
        migrations.CreateModel(
            name='Transformacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proceso_lavado', models.TextField(help_text='Descripción del proceso de lavado aplicado', verbose_name='Proceso de Lavado')),
                ('fecha_lavado', models.DateTimeField(verbose_name='Fecha de Lavado')),
                ('proceso_empaquetado', models.TextField(help_text='Descripción del proceso de empaquetado', verbose_name='Proceso de Empaquetado')),
                ('fecha_empaquetado', models.DateTimeField(verbose_name='Fecha de Empaquetado')),
                ('control_calidad', models.CharField(choices=[('APROBADO', 'Aprobado'), ('RECHAZADO', 'Rechazado')], help_text='Resultado del control de calidad', max_length=20, verbose_name='Control de Calidad')),
                ('observaciones_calidad', models.TextField(blank=True, null=True, verbose_name='Observaciones de Calidad')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Registro')),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transformaciones', to='data.lote', verbose_name='Lote')),
            ],
            options={
                'verbose_name': 'Transformación',
                'verbose_name_plural': 'Transformaciones',
                'db_table': 'transformaciones',
                'ordering': ['-fecha_empaquetado'],
            },
        ),
        migrations.CreateModel(
            name='Logistica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperatura_transporte', models.DecimalField(decimal_places=2, help_text='Temperatura promedio durante el transporte', max_digits=5, validators=[django.core.validators.MinValueValidator(-20), django.core.validators.MaxValueValidator(50)], verbose_name='Temperatura de Transporte (°C)')),
                ('fecha_inicio_transporte', models.DateTimeField(verbose_name='Fecha de Inicio de Transporte')),
                ('fecha_entrega_supermercado', models.DateTimeField(verbose_name='Fecha de Entrega al Supermercado')),
                ('nombre_supermercado', models.CharField(help_text='Nombre del supermercado de destino', max_length=200, verbose_name='Nombre del Supermercado')),
                ('direccion_supermercado', models.CharField(max_length=300, verbose_name='Dirección del Supermercado')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Registro')),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logisticas', to='data.lote', verbose_name='Lote')),
            ],
            options={
                'verbose_name': 'Logística',
                'verbose_name_plural': 'Logísticas',
                'db_table': 'logisticas',
                'ordering': ['-fecha_entrega_supermercado'],
            },
        ),
    ]
